// Central config for all supported lottery types.

export const LOTTERIES = {
  western_649: {
    id: 'western_649',
    name: 'Western 6/49',
    icon: '🎱',
    region: 'AB / SK / MB',
    numbersPerLine: 6,
    numberMax: 49,
    hasExtra: true,
    extraLabel: 'EXTRA',
    extraHint: '7 digits, e.g. 2345671',
    hasExtra2: false,
    hasBonus: true,
    bonusLabel: 'Bonus',
    bonusMax: 49,
    drawDays: 'Wed & Sat',
    description: '6/49 · Wed & Sat',
  },
  lotto_649: {
    id: 'lotto_649',
    name: 'Lotto 6/49',
    icon: '🍀',
    region: 'National',
    numbersPerLine: 6,
    numberMax: 49,
    hasExtra: true,
    extraLabel: 'Gold Ball',
    extraHint: 'e.g. 08009419-01',
    hasExtra2: true,
    extra2Label: 'EXTRA',
    extra2Hint: 'e.g. 24-26-42-65-YES',
    hasBonus: true,
    bonusLabel: 'Bonus',
    bonusMax: 49,
    drawDays: 'Wed & Sat',
    description: '6/49 · Wed & Sat',
  },
  lotto_max: {
    id: 'lotto_max',
    name: 'Lotto Max',
    icon: '💰',
    region: 'National',
    numbersPerLine: 7,
    numberMax: 52,
    hasExtra: false,
    hasExtra2: false,
    hasBonus: true,
    bonusLabel: 'Bonus',
    bonusMax: 52,
    drawDays: 'Tue & Fri',
    description: '7/52 · Tue & Fri',
  },
  daily_grand: {
    id: 'daily_grand',
    name: 'Daily Grand',
    icon: '👑',
    region: 'National',
    numbersPerLine: 5,
    numberMax: 49,
    hasExtra: false,
    hasExtra2: false,
    hasBonus: true,
    bonusLabel: 'Grand #',
    bonusMax: 7,
    drawDays: 'Mon & Thu',
    description: '5/49 · Mon & Thu',
  },
  bc_49: {
    id: 'bc_49',
    name: 'BC/49',
    icon: '🌲',
    region: 'BC',
    numbersPerLine: 6,
    numberMax: 49,
    hasExtra: true,
    extraLabel: 'EXTRA',
    extraHint: 'e.g. 23-45-67-1',
    hasExtra2: false,
    hasBonus: true,
    bonusLabel: 'Bonus',
    bonusMax: 49,
    drawDays: 'Wed & Sat',
    description: '6/49 · Wed & Sat',
  },
  western_max: {
    id: 'western_max',
    name: 'Western Max',
    icon: '⚡',
    region: 'AB / SK / MB',
    numbersPerLine: 7,
    numberMax: 50,
    hasExtra: true,
    extraLabel: 'EXTRA',
    extraHint: '7 digits, e.g. 2345671',
    hasExtra2: false,
    hasBonus: true,
    bonusLabel: 'Bonus',
    bonusMax: 50,
    drawDays: 'Tue & Fri',
    description: '7/50 · Tue & Fri',
  },
}

export function getLottery(id) {
  return LOTTERIES[id] || LOTTERIES['western_649']
}
